name: Incident
about: Create an incident notification on the status website
title: '[Incident] Service is unavailable'
labels: 'status'
assignees: 'retirable/core'
body:
- type: markdown
  attributes:
    value: "Make sure you add the affected service (eg `retirable-app`, `retirable-website`) as a label"
- type: textarea
  id: summary
  attributes:
    label: Summary of Incident
    description: "Provide a high-level description of the incident. This will be displayed publicly on the status page"
    placeholder: "Submitting the form on page x results in problem y"
